### ISSUE TITLE
low training speed on S3DIS?

### ISSUE THREAD

**Issue by tangze5258** [MIC-DKFZ/MedNeXt#17]
every epoch took about 6000 s , somgthing wrong?

**Comment by tangze5258** [comment]
how to predict single *.nii file if the  model trianing ends?

**Comment by saikat-roy** [comment]
Hey @tangze5258. Sorry for the late reply. You can use the following `mednextv1_predict` instead of `nnUNet_predict` as in the example [here](https://github.com/MIC-DKFZ/MedNeXt/blob/main/documentation/inference_example_Prostate.md) for inference on single files.

I have never trained on S3DIS but the training speeds depend heavily on the CPU, type of storage the training data is on (HDD, SSD etc) and the GPU used. If you could tell me about your configuration, I could confirm whether this indeed is the issue.
