### ISSUE TITLE
several import errors

### ISSUE THREAD

**Issue by Bruce1973** [MIC-DKFZ/MedNeXt#2]
Hi,
    Thanks for your great job about the MedNeXt. I found several import errors while running the code, the followings are my advice for the bug fix，please consider it carefully!
![image](https://github.com/MIC-DKFZ/MedNeXt/assets/34022969/09c2cfb1-5c70-483f-8b84-701efac27f19)
![image](https://github.com/MIC-DKFZ/MedNeXt/assets/34022969/efd69420-2ee7-47c6-b5c3-6d58409e7a23)
![image](https://github.com/MIC-DKFZ/MedNeXt/assets/34022969/903558e8-8a8a-4d65-bc89-1ff7393e2e08)
![image](https://github.com/MIC-DKFZ/MedNeXt/assets/34022969/5fb0cd10-4e3a-447c-a521-f2a75c8c8755)

**Comment by saikat-roy** [comment]
Hey @Bruce1973. Thanks for the report. These are because I haven't tested the nnunet training on this repo yet and haven't completed the refactoring (as well as the nnunet training instructions in the documentation). Your changes seem to fix everything.

I could recreate them on my end or you could send a PR if you want.

**Comment by saikat-roy** [comment]
Fixed in #3.
