### ISSUE TITLE
How to train MedNeXt

### ISSUE THREAD

**Issue by lovergos** [MIC-DKFZ/MedNeXt#5]
Dear author,
Thank you for your good job，I want to ask you about the training process, and how to train MedNeXt,

**Comment by saikat-roy** [comment]
Hey @lovergos . I'm sorry but I simply haven't had the time to clean the code for the training yet. I trained it by creating a nnunet v1 trainer - that is, by replacing the architecture inside a standard `nnUNetTrainerV2` subclass and using patches of size `128 x 128 x 128`

This should not be hard to replicate if you have experience with nnUNet v1. However, I will have code for this training in the near future. 

If you have any other questions on the training process, please let me know. Otherwise, keep an eye out for an update to the repo for the training code.

**Comment by saikat-roy** [comment]
There is code and instructions now to recreate the MICCAI2023 experiments in nnUNet(v1). Please reopen this issue if you have more questions.
