### ISSUE TITLE
Cannot find 'nnunet_mednext.network_architecture.custom_modules.custom_networks'

### ISSUE THREAD

**Issue by Healingl** [MIC-DKFZ/MedNeXt#6]
Hi, this is a great job! And I want to learn some transformer modules from this project, but I cannot find 'nnunet_mednext.network_architecture.custom_modules.custom_networks' in this project. Could you help me?

**Comment by saikat-roy** [comment]
Hey @Healingl. I did not include the Transformer networks for the baselines of this project since nearly all of the code is available in the original repositories:

- UNETR: https://github.com/project-monai/monai
- SWINUNETR: https://github.com/project-monai/monai
- TransUNet: https://github.com/Beckschen/TransUNet
- TransBTS: https://github.com/Wenxuan-1119/TransBTS
- nnFormer: https://github.com/282857341/nnFormer
- 3D-UX-Net: https://github.com/MASILab/3DUX-Net

I adopted everything from the original repositories. That should help you explore the code.

**Comment by Healingl** [comment]
> Hey @Healingl. I did not include the Transformer networks for the baselines of this project since nearly all of the code is available in the original repositories:
> 
> * UNETR: https://github.com/project-monai/monai
> * SWINUNETR: https://github.com/project-monai/monai
> * TransUNet: https://github.com/Beckschen/TransUNet
> * TransBTS: https://github.com/Wenxuan-1119/TransBTS
> * nnFormer: https://github.com/282857341/nnFormer
> * 3D-UX-Net: https://github.com/MASILab/3DUX-Net
> 
> I adopted everything from the original repositories. That should help you explore the code.

**Comment by Healingl** [comment]
Thanks
